
2020-07-17 13:22:15,693:INFO:train.py:<module>:146:
{
    "cuda": false,
    "seed": 1234,
    "shuffle": true,
    "data_url": "https://raw.githubusercontent.com/madewithml/lessons/master/data/news.csv",
    "lower": true,
    "char_level": false,
    "filters": "[!\\\"'#$%&()*\\+,-./:;<=>?@\\\\\\[\\]^_`{|}~]",
    "data_size": 1.0,
    "train_size": 0.7,
    "val_size": 0.15,
    "test_size": 0.15,
    "num_epochs": 10,
    "batch_size": 64,
    "embedding_dim": 100,
    "use_glove": true,
    "freeze_embeddings": false,
    "filter_sizes": [
        2,
        3,
        4
    ],
    "num_filters": 50,
    "hidden_dim": 128,
    "dropout_p": 0.1,
    "learning_rate": 0.0001,
    "patience": 3
}

2020-07-17 13:22:16,950:INFO:train.py:<module>:158:
Raw data:
  Sharon Accepts Plan to Reduce Gaza Army Operation, Haaretz Says World

2020-07-17 13:22:17,657:INFO:train.py:<module>:165:
Preprocessed data:
  Sharon Accepts Plan to Reduce Gaza Army Operation, Haaretz Says → Sharon Accepts Plan to Reduce Gaza Army Operation , Haaretz Says

2020-07-17 13:22:17,857:INFO:train.py:<module>:172:
Data splits:
	X_train: 86700, y_train: 86700
	X_val: 15300, y_val: 15300
	X_test: 18000, y_test: 18000

2020-07-17 13:22:18,713:INFO:train.py:<module>:183:
vocab_size: 29794

2020-07-17 13:22:19,843:INFO:train.py:<module>:192:
Text to indices:
  (raw) Fed , Corporate Forecasts to Set Tone
  (preprocessed) fed corporate forecasts to set tone
  (tokenized) [374, 1266, 1419, 2, 70, 4780]

2020-07-17 13:22:19,845:INFO:train.py:<module>:202:
classes:
  ['Business' 'Sci/Tech' 'Sports' 'World']

2020-07-17 13:22:19,859:INFO:train.py:<module>:211:
Labels to indices:
  Business → 0

2020-07-17 13:22:19,861:INFO:train.py:<module>:218:
class counts:
  [21675 21675 21675 21675]
class weights:
  {0: 4.61361014994233e-05, 1: 4.61361014994233e-05, 2: 4.61361014994233e-05, 3: 4.61361014994233e-05}

2020-07-17 13:22:19,863:INFO:train.py:<module>:235:
Dataset generators:
  (training_generator) <DataGenerator(batch_size=64, batches=1355, shuffle=False)>
  (validation_generator) <DataGenerator(batch_size=64, batches=240, shuffle=False)>
  (testing_generator) <DataGenerator(batch_size=64, batches=282, shuffle=False)>
Sample batch:
  X: (64, 13)
  y: (64,)


2020-07-17 13:22:32,188:INFO:train.py:<module>:257:
GloVe Embeddings:
(29794, 100)
Traceback (most recent call last):
  File "text_classification/train.py", line 287, in <module>
    callbacks=callbacks, shuffle=False, class_weight=class_weights, verbose=1)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\wandb\keras\__init__.py", line 120, in new_v2
    return old_v2(*args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1063, in fit
    steps_per_execution=self._steps_per_execution)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 1117, in __init__
    model=model)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 916, in __init__
    **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 794, in __init__
    lambda x: model(x, training=False), args=(concrete_x,))
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 1211, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 2585, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\distribute\distribute_lib.py", line 2945, in _call_for_each_replica
    return fn(*args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\keras\engine\data_adapter.py", line 794, in <lambda>
    lambda x: model(x, training=False), args=(concrete_x,))
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\text_classification\models.py", line 52, in call
    z = self.convs[i](x_embed)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 985, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\keras\layers\convolutional.py", line 247, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1018, in convolution_v2
    name=name)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1148, in convolution_internal
    name=name)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\util\deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\util\deprecation.py", line 574, in new_func
    return func(*args, **kwargs)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1889, in conv1d
    name=name)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 938, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\mahjo\e2e-ml-app-tensorflow\venv\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above. [Op:Conv2D]
